### ISSUE TITLE
why you left?

### ISSUE THREAD

**Issue by Grace5921** [S6310-Development/android_device_samsung_msm7x27a-common#2]
i know this is old device and has got some bugs in cm12 but still i have made cm13 for i8552 using your works :D and bugs are bt , cam reset works fine and i am really in need of your help to fix remaning bugs if you helped me then i will make cm13 for your device too :D

**Comment by lesleyxxx12** [comment]
I left because I do not own the device anymore.. I currently own a Nexus 6P and develop for the device.
Closing Issue. Send me an email for future questions.

**Comment by Grace5921** [comment]
a question what's your email ?

**Comment by lesleyxxx12** [comment]
It's on my profile

**Comment by Grace5921** [comment]
ok thanks
